name: Update EasyDutch CDN

on:
  schedule:
    - cron: "00 12,20 * * *"
  workflow_dispatch:

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Update EasyDutch CDN
    runs-on: ubuntu-latest
    steps:
      - name: Clone EasyDutchCDN
        uses: actions/checkout@v3
      - name: Copy EasyDutch filters to EasyDutchCDN
        run: |
          TMPFILE=$(mktemp -d)
          git clone --depth=1 --single-branch --branch=gh-pages https://github.com/EasyDutch-uBO/EasyDutch.git $TMPFILE
          cp $TMPFILE/EasyDutch/*.txt EasyDutch/
          cp $TMPFILE/EasyDutch.txt EasyDutch.txt
          cp $TMPFILE/EasyDutch/EasyDutch.all.txt EasyDutch.all.txt
      - name: Commit changes (if any)
        run: |
          if [[ -n $(git diff) ]]; then
            git config user.name "GitHub Actions"
            git config user.email "<>"
            git add -u EasyDutch/ EasyDutch.txt EasyDutch.all.txt
            git commit -m "Update all CDN assets"
            git push origin main
          fi
