name: Delete old workflow runs
on:
  workflow_dispatch:
  schedule:
    - cron: '00 03 * * 1'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: Update EasyDutch CDN
          retain_days: 0
          keep_minimum_runs: 3
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: pages build and deployment
          retain_days: 0
          keep_minimum_runs: 1
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: Delete old workflow runs
          retain_days: 0
          keep_minimum_runs: 1

