name: Update EasyDutch CDN

on:
  schedule:
    - cron: "00 12 * * *"
  workflow_dispatch:

jobs:
  publish:
    name: Update EasyDutch CDN
    runs-on: ubuntu-latest
    steps:
      - name: Clone EasyDutchCDN
        uses: actions/checkout@v3
      - name: Copy EasyDutch filters to uAssetsCDN
        run: |
          TMPDIR=$(mktemp -d)
          git clone --depth=1 --single-branch --branch=gh-pages https://github.com/EasyDutch-uBO/EasyDutch.git $TMPDIR
          cp $TMPDIR/EasyDutch/*.txt EasyDutch/
          cp $TMPDIR/EasyDutch.txt
      - name: Commit changes, if any
        run: |
          if [[ -n $(git diff) ]]; then
            git config user.name "GitHub Actions"
            git config user.email "<>"
            git add -u EasyDutch/
            git commit -m "Update all CDN assets"
            git push origin main
          fi
